### ISSUE TITLE
Map background image

### ISSUE THREAD

**Issue by adamlocker** [HiredThought/wardley-mapping-kumu#1]
This is **_brilliant_** and I love using it but is there a version of the background template without the background explanatory text on it that we could use as on more complex maps it can be a little busy.

**Comment by bemosior** [comment]
Adam! So glad you've found it useful! That's an easy enough request. Let me see what I can do.

**Comment by bemosior** [comment]
Added via https://github.com/HiredThought/wardley-mapping-kumu/commit/6e75032db76f3285c216ea257c4723155c645e57. Let me know if you need anything adjusted!
